<?php

/**
 * Register View API information.
 */
function smash2013ws_views_handlers_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'smash2013ws_views_handlers') . '/views_handlers.inc',
  );
}

/**
 * Implements hook_views_data().
 */
function smash2013ws_views_handlers_views_data() {

  $data['node']['created_year_month_format'] = array(
    'title' => t('Created year - month'),
    'help' => t('Date in the form of YYYY-MM.'),
    'argument' => array(
      'field' => 'changed',
      'handler' => 'views_handler_argument_node_created_year_month_spaced',
    ),
  );

  $data['node']['updated_year_month_format'] = array(
    'title' => t('Updated year - month'),
    'help' => t('Date in the form of YYYY-MM.'),
    'argument' => array(
      'field' => 'changed',
      'handler' => 'views_handler_argument_node_updated_year_month_spaced',
    ),
  );

}
